version: "3.9"
services:
  backend:
    image: "rehcems/springboot-react-fullstack:2.4.2021.13.36.20"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
